clash-for-windows: installer from exe format to 7z format
chawyehsu/dorado pull request #779
Opened 2023-09-27 11:50 UTC by junlongzzz

将cfw的 `exe` 格式安装改为 `7z` 格式

2023-09-27 11:51 UTC, junlongzzz commented
#770

2023-10-04 03:54 UTC, chawyehsu requested changes

2023-10-04 03:54 UTC, chawyehsu commented on bucket/clash-for-windows.json
> +            "$runtimeCache = \"$env:APPDATA\\clash_win\"",
Please do not change the installer script, it handles well already.

2023-10-05 05:57 UTC, chawyehsu approved these changes

2023-10-05 05:57 UTC, merged